### ISSUE TITLE
HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by walterqianTest1** [microsoft/dicom-server#801]
**Describe the bug**
I can not deploy to non-production slot from Azure DevOps to Azure App Service. The deployment was successful in Azure DevOps but when I browser the non-production slot, error message shows that: 

```
HTTP Error 500.30 - ASP.NET Core app failed to start Common solutions to this issue:
The app failed to start
The app started but then stopped
The app started but threw an exception during startup
```

Here is the error message in the eventlog.xml:

```
Could not find 'aspnetcorev2_inprocess.dll'. Exception message:
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.6' was not found.
  - The following frameworks were found:
      2.1.26 at [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
      2.2.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
      3.0.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
      3.1.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
      5.0.4 at [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

However, when I deploy to production slot it worked fine.
I also installed the extension: ASP.NET Core 5.0 (x64) Runtime version:5.0.6 but still have this issue. 
Please help me resolve this issue. 

**To Reproduce**
1. Click the "Deploy to Azure" button in github. 
2. Create testslot and copy the settings.
3. Deploy to test slot from Azure DevOps with the yaml file in Build folder.
4. Browse test slot in App Service and the receive error message.

**Expected behavior**
We can deploy this source code to non-production slot.

**Actual behavior**
Error message shows that: HTTP Error 500.30 - ASP.NET Core app failed to start.

**Comment by wsugarman** [comment]
For step (3), are you referring to repository's build folder? That folder contains our own CI/CD pipelines, and it's not meant for use outside of our own CI/CD scenarios. So, I am unsure exactly what your pipelines look like for deploying to a particular app service slot.

That being said, copying the settings for a slot will not copy the extensions. So be sure to check if the test slot _also_ has the ASP.NET Core 5.0 x64 extension for version 5.0.6. Slots appear to have separate extensions.

**Comment by walterqianTest1** [comment]
Yes. I'm referring to the repository's build folder but I made some changes. Here is the artifacts published from build pipeline:
![image](https://user-images.githubusercontent.com/57620509/119939195-0c8b1680-bfc0-11eb-86b6-1e2503ad60bb.png)
After that, I deployed to the testslot with this YAML:
```
steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '{}'
    pipeline: '{}'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'deploy'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '{}'
    appType: 'webApp'
    WebAppName: '{}'
    deployToSlotOrASE: true
    ResourceGroupName: '{}'
    SlotName: 'testslot'
    Package: '$(System.ArtifactsDirectory)/deploy/Microsoft.Health.Dicom.Web.zip'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'
```
In addition, I also created a new App Service and deployed to it with the same issue. I installed ASP.NET Core 5.0 x64 extension for version 5.0.6 and I also tried to install other versions of extension but still have this issue. 

So, my question is that, how can we create a non-production slot in Azure App Service and deploy this sample from Azure Devops? Or do you know where else we can check? 
I can contact you if a remote session is needed.
